### ISSUE TITLE
After submitting 4000 transactions, they slowly trickle into transaction_pool. See if this can be improved

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari-dan#723]
To replicate:
Submit 4000 transactions
The transaction_submitter ends quickly.
Then repeatedly run 
```sql
select count(*) as mempool, sum(case when stage = 'AllPrepared' then 1 else 0 end) as all_prepared,
       sum(case when stage = 'LocalPrepared' then 1 else 0 end) as local_prepared,
         sum(case when stage = 'Prepared' then 1 else 0 end) as prepared,
            sum(case when stage = 'New' then 1 else 0 end) as new
from transaction_pool;
```

Expected: 
All 4000 should be there in New

Actual:
Transactions appear in New (count goes up) at a rate of about 5 txs a second

Was tested using 5 vns on dan-testing 

Cifko:
I haven't encountered the issue above, but the 4000 transactions was slow. In total (for all 4000 txs)
- 122 seconds was the inserting into the DB
  - 8 second out of it is the creation of the db row,
  - less than one second is hex and json conversion
  - the rest is the `tx.commit`
- 58 seconds was gossiping

So on average the whole transaction is 0.046 seconds (~22 tx/sec).

**Comment by stringhandler** [comment]
seems like sqlite is the limit here. We use sqlite for easy debugging. Perhaps it's time to try a more performant db

**Comment by therealdannzor** [comment]
Considering the fact it's been some time since this ticket was opened, it looks like this particular scenario has been resolved, using:
* 5 validator nodes
* 4000 txs submitted

### Submitting transactions through `transaction_submitter`

All went through within a minute:

![dan_node_tx_submission](https://github.com/user-attachments/assets/abd86152-6b1e-4cfc-ba82-cd472ea55e1c)

### Verifying the transaction pool for pending or stuck ones

The tx pool was shown to be completely empty:

![dan_mempool](https://github.com/user-attachments/assets/09f21e4c-5cee-4815-8682-66f81a37b527)

### Looking at the block history for a node

Details and confirmations can be seen at the block history page:

![dan_node_blocks](https://github.com/user-attachments/assets/c924591d-ac46-441d-8c89-2f6abb6aa280)

### Final confirmation of transactions

Confirming in the database that txs have been executed:

![dan_tx_executed](https://github.com/user-attachments/assets/0e24b367-7f1a-4cdd-93e3-bd78da542b6d)

Anything missing? @sdbondi cc @stringhandler

**Comment by sdbondi** [comment]
Nice, I think we can close this one. Feel free to reopen if there's something else for this ticket.
